In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import ensemble
from sklearn.model_selection import cross_val_score
%matplotlib inline

In [2]:
y2015 = pd.read_csv(
    'https://www.dropbox.com/s/0so14yudedjmm5m/LoanStats3d.csv?dl=1',
    skipinitialspace=True,
    header=1
)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\IPython\core\interactiveshell.py:3044: DtypeWarning: Columns (0,19,55) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [3]:
categorical = y2015.select_dtypes(include=['object'])
for i in categorical:
    column = categorical[i]
    print(i)
    print(column.nunique())

id
421097
term
2
int_rate
110
grade
7
sub_grade
35
emp_title
120812
emp_length
11
home_ownership
4
verification_status
3
issue_d
12
loan_status
7
pymnt_plan
1
url
421095
desc
34
purpose
14
title
27
zip_code
914
addr_state
49
earliest_cr_line
668
revol_util
1211
initial_list_status
2
last_pymnt_d
25
next_pymnt_d
4
last_credit_pull_d
26
application_type
2
verification_status_joint
3


In [4]:
# Convert ID and Interest Rate to numeric.
y2015['id'] = pd.to_numeric(y2015['id'], errors='coerce')
y2015['int_rate'] = pd.to_numeric(y2015['int_rate'].str.strip('%'), errors='coerce')

# Drop other columns with many unique variables
y2015.drop(['url', 'emp_title', 'zip_code', 'earliest_cr_line', 'revol_util',
            'sub_grade', 'addr_state', 'desc'], 1, inplace=True)

In [5]:
y2015 = y2015[:-2]

In [6]:
rfc = ensemble.RandomForestClassifier()
X = y2015.drop('loan_status', 1)
Y = y2015['loan_status']
X = pd.get_dummies(X)
X = X.dropna(axis=1)

cross_val_score(rfc, X, Y, cv=10)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in versio

array([0.97962528, 0.98067013, 0.98143003, 0.98185747, 0.96991213,
       0.97876989, 0.92673775, 0.98071671, 0.98009832, 0.9802166 ])

### Data Cleaning

In [6]:
## create a correlation matrix that is sorted
c = y2015.corr().abs()

s = c.unstack()
so = s.sort_values(kind="quicksort", ascending=False)

pd.set_option('display.max_rows', 5000)
print(so)

total_il_high_credit_limit      total_il_high_credit_limit        1.000000
bc_util                         bc_util                           1.000000
mths_since_recent_bc            mths_since_recent_bc              1.000000
mort_acc                        mort_acc                          1.000000
mo_sin_rcnt_tl                  mo_sin_rcnt_tl                    1.000000
mo_sin_rcnt_rev_tl_op           mo_sin_rcnt_rev_tl_op             1.000000
mo_sin_old_rev_tl_op            mo_sin_old_rev_tl_op              1.000000
mo_sin_old_il_acct              mo_sin_old_il_acct                1.000000
delinq_amnt                     delinq_amnt                       1.000000
chargeoff_within_12_mths        chargeoff_within_12_mths          1.000000
bc_open_to_buy                  bc_open_to_buy                    1.000000
mths_since_recent_inq           mths_since_recent_inq             1.000000
avg_cur_bal                     avg_cur_bal                       1.000000
acc_open_past_24mths     

In [7]:
## remove highly correlated values
y2015 = y2015.drop(columns = ['out_prncp_inv','total_pymnt', 'funded_amnt_inv', 'num_sats', 'member_id', 'num_rev_tl_bal_gt_0',\
                    'tot_hi_cred_lim', 'collection_recovery_fee', 'total_rec_prncp', 'total_bal_il', 'installment', \
                    'mths_since_recent_bc_dlq', 'total_bal_ex_mort', 'percent_bc_gt_75', 'open_rv_24m', 'num_rev_accts',\
                    'num_bc_sats', 'avg_cur_bal', 'total_rev_hi_lim', 'open_rv_12m', 'num_op_rev_tl', 'total_bc_limit',\
                    'last_pymnt_amnt'])

In [8]:
## recreate sorted correlation matrix
c1 = y2015.corr().abs()

s1 = c1.unstack()
so1 = s1.sort_values(kind="quicksort", ascending=False)

pd.set_option('display.max_rows', 5000)
print(so1)

total_il_high_credit_limit      total_il_high_credit_limit        1.000000
mo_sin_rcnt_tl                  mo_sin_rcnt_tl                    1.000000
max_bal_bc                      max_bal_bc                        1.000000
all_util                        all_util                          1.000000
inq_fi                          inq_fi                            1.000000
total_cu_tl                     total_cu_tl                       1.000000
inq_last_12m                    inq_last_12m                      1.000000
acc_open_past_24mths            acc_open_past_24mths              1.000000
bc_open_to_buy                  bc_open_to_buy                    1.000000
bc_util                         bc_util                           1.000000
chargeoff_within_12_mths        chargeoff_within_12_mths          1.000000
delinq_amnt                     delinq_amnt                       1.000000
mo_sin_old_il_acct              mo_sin_old_il_acct                1.000000
mo_sin_old_rev_tl_op     

In [9]:
## remove more columns
y2015 = y2015.drop(columns = ['mths_since_last_delinq', 'num_actv_bc_tl', 'num_tl_30dpd', 'acc_open_past_24mths',\
                             'open_il_24m', 'open_acc_6m', 'total_rec_int', 'total_rec_int', 'tax_liens', 'annual_inc',\
                             'total_acc'])

In [10]:
## recreate sorted correlation matrix
c2 = y2015.corr().abs()

s2 = c2.unstack()
so2 = s2.sort_values(kind="quicksort", ascending=False)

pd.set_option('display.max_rows', 5000)
print(so2)

total_il_high_credit_limit      total_il_high_credit_limit        1.000000
mths_since_rcnt_il              mths_since_rcnt_il                1.000000
all_util                        all_util                          1.000000
inq_fi                          inq_fi                            1.000000
total_cu_tl                     total_cu_tl                       1.000000
inq_last_12m                    inq_last_12m                      1.000000
bc_open_to_buy                  bc_open_to_buy                    1.000000
bc_util                         bc_util                           1.000000
chargeoff_within_12_mths        chargeoff_within_12_mths          1.000000
delinq_amnt                     delinq_amnt                       1.000000
mo_sin_old_il_acct              mo_sin_old_il_acct                1.000000
mo_sin_old_rev_tl_op            mo_sin_old_rev_tl_op              1.000000
mo_sin_rcnt_rev_tl_op           mo_sin_rcnt_rev_tl_op             1.000000
mo_sin_rcnt_tl           

In [11]:
## remove more columns
y2015 = y2015.drop(columns = ['total_pymnt_inv', 'funded_amnt', 'num_actv_rev_tl', 'open_il_6m', 'delinq_2yrs', 'out_prncp',\
                             'mo_sin_rcnt_rev_tl_op', 'pub_rec_bankruptcies', 'mths_since_recent_bc'])

In [15]:
## Run Random Forest with cleaned data
rfc1 = ensemble.RandomForestClassifier()
X1 = y2015.drop('loan_status', 1)
Y1 = y2015['loan_status']
X1 = pd.get_dummies(X1)
X1 = X1.dropna(axis=1)

cross_val_score(rfc1, X1, Y1, cv=10)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in versio

array([0.92196813, 0.93585999, 0.92959084, 0.9232742 , 0.90949893,
       0.92348611, 0.90833314, 0.94264884, 0.92880044, 0.94694343])

In [12]:
## recreate sorted correlation matrix
c3 = y2015.corr().abs()

s3 = c3.unstack()
so3 = s3.sort_values(kind="quicksort", ascending=False)

pd.set_option('display.max_rows', 5000)
print(so3)

total_il_high_credit_limit      total_il_high_credit_limit        1.000000
mo_sin_old_rev_tl_op            mo_sin_old_rev_tl_op              1.000000
inq_fi                          inq_fi                            1.000000
total_cu_tl                     total_cu_tl                       1.000000
inq_last_12m                    inq_last_12m                      1.000000
bc_open_to_buy                  bc_open_to_buy                    1.000000
bc_util                         bc_util                           1.000000
chargeoff_within_12_mths        chargeoff_within_12_mths          1.000000
delinq_amnt                     delinq_amnt                       1.000000
mo_sin_old_il_acct              mo_sin_old_il_acct                1.000000
mo_sin_rcnt_tl                  mo_sin_rcnt_tl                    1.000000
max_bal_bc                      max_bal_bc                        1.000000
mort_acc                        mort_acc                          1.000000
mths_since_recent_inq    

In [13]:
y2015 = y2015.drop(columns = ['num_il_tl', 'bc_util', 'max_bal_bc', 'num_tl_op_past_12m', 'all_util', 'inq_last_12m',\
                              'num_accts_ever_120_pd', 'mths_since_recent_inq', 'mths_since_last_major_derog', 'open_acc', \
                              'annual_inc_joint'])

In [18]:
## Run Random Forest with cleaned data
rfc2 = ensemble.RandomForestClassifier()
X2 = y2015.drop('loan_status', 1)
Y2 = y2015['loan_status']
X2 = pd.get_dummies(X2)
X2 = X2.dropna(axis=1)

cross_val_score(rfc2, X2, Y2, cv=10)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in versio

array([0.93227423, 0.93543255, 0.92203937, 0.93353281, 0.90301591,
       0.92652577, 0.90607709, 0.94447743, 0.94219488, 0.92993873])

In [14]:
## recreate sorted correlation matrix
c4 = y2015.corr().abs()

s4 = c4.unstack()
so4 = s4.sort_values(kind="quicksort", ascending=False)

pd.set_option('display.max_rows', 5000)
print(so4)

total_il_high_credit_limit      total_il_high_credit_limit        1.000000
open_il_12m                     open_il_12m                       1.000000
num_tl_120dpd_2m                num_tl_120dpd_2m                  1.000000
num_bc_tl                       num_bc_tl                         1.000000
mths_since_recent_revol_delinq  mths_since_recent_revol_delinq    1.000000
mort_acc                        mort_acc                          1.000000
mo_sin_rcnt_tl                  mo_sin_rcnt_tl                    1.000000
mo_sin_old_rev_tl_op            mo_sin_old_rev_tl_op              1.000000
mo_sin_old_il_acct              mo_sin_old_il_acct                1.000000
delinq_amnt                     delinq_amnt                       1.000000
chargeoff_within_12_mths        chargeoff_within_12_mths          1.000000
bc_open_to_buy                  bc_open_to_buy                    1.000000
total_cu_tl                     total_cu_tl                       1.000000
inq_fi                   

In [15]:
y2015 = y2015.drop(columns = ['tot_cur_bal', 'open_il_12m', 'bc_open_to_buy', 'total_il_high_credit_limit'])

In [21]:
## Run Random Forest with cleaned data
rfc3 = ensemble.RandomForestClassifier()
X3 = y2015.drop('loan_status', 1)
Y3 = y2015['loan_status']
X3 = pd.get_dummies(X3)
X3 = X3.dropna(axis=1)

cross_val_score(rfc3, X3, Y3, cv=10)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in versio

array([0.92823728, 0.93020826, 0.92792857, 0.92417658, 0.90676799,
       0.93006412, 0.92260562, 0.94013156, 0.93839504, 0.93435615])

In [16]:
## recreate sorted correlation matrix
c5 = y2015.corr().abs()

s5 = c5.unstack()
so5 = s5.sort_values(kind="quicksort", ascending=False)

pd.set_option('display.max_rows', 5000)
print(so5)

pct_tl_nvr_dlq                  pct_tl_nvr_dlq                    1.000000
tot_coll_amt                    tot_coll_amt                      1.000000
num_bc_tl                       num_bc_tl                         1.000000
mths_since_recent_revol_delinq  mths_since_recent_revol_delinq    1.000000
mort_acc                        mort_acc                          1.000000
mo_sin_rcnt_tl                  mo_sin_rcnt_tl                    1.000000
mo_sin_old_rev_tl_op            mo_sin_old_rev_tl_op              1.000000
mo_sin_old_il_acct              mo_sin_old_il_acct                1.000000
delinq_amnt                     delinq_amnt                       1.000000
chargeoff_within_12_mths        chargeoff_within_12_mths          1.000000
total_cu_tl                     total_cu_tl                       1.000000
inq_fi                          inq_fi                            1.000000
il_util                         il_util                           1.000000
acc_now_delinq           

In [17]:
y2015 = y2015.drop(columns = ['mths_since_rcnt_il', 'acc_now_delinq', 'mths_since_rcnt_il', 'revol_bal',\
                              'mo_sin_old_rev_tl_op'])

In [27]:
## Run Random Forest with cleaned data
rfc4 = ensemble.RandomForestClassifier()
X4 = y2015.drop('loan_status', 1)
Y4 = y2015['loan_status']
X4 = pd.get_dummies(X4)
X4 = X4.dropna(axis=1)

cross_val_score(rfc4, X4, Y4, cv=10)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in versio

array([0.92059082, 0.93574126, 0.91598395, 0.92099451, 0.91840418,
       0.92429352, 0.90477095, 0.93825548, 0.92549932, 0.88077709])

In [18]:
## recreate sorted correlation matrix
c6 = y2015.corr().abs()

s6 = c6.unstack()
so6 = s6.sort_values(kind="quicksort", ascending=False)

print(so6)

pct_tl_nvr_dlq                  pct_tl_nvr_dlq                    1.000000
tot_coll_amt                    tot_coll_amt                      1.000000
num_bc_tl                       num_bc_tl                         1.000000
mths_since_recent_revol_delinq  mths_since_recent_revol_delinq    1.000000
mort_acc                        mort_acc                          1.000000
mo_sin_rcnt_tl                  mo_sin_rcnt_tl                    1.000000
mo_sin_old_il_acct              mo_sin_old_il_acct                1.000000
delinq_amnt                     delinq_amnt                       1.000000
chargeoff_within_12_mths        chargeoff_within_12_mths          1.000000
total_cu_tl                     total_cu_tl                       1.000000
inq_fi                          inq_fi                            1.000000
dti_joint                       dti_joint                         1.000000
num_tl_90g_dpd_24m              num_tl_90g_dpd_24m                1.000000
collections_12_mths_ex_me

In [19]:
y2015 = y2015.drop(columns = ['int_rate', 'pct_tl_nvr_dlq', 'pub_rec', 'num_tl_120dpd_2m', 'inq_last_6mths'])

In [20]:
## Run Random Forest with cleaned data
rfc5 = ensemble.RandomForestClassifier()
X5 = y2015.drop('loan_status', 1)
Y5 = y2015['loan_status']
X5 = pd.get_dummies(X5)
X5 = X5.dropna(axis=1)

cross_val_score(rfc5, X5, Y5, cv=10)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in versio

array([0.92830852, 0.92560139, 0.93215549, 0.92089953, 0.90774163,
       0.9217763 , 0.90163623, 0.93808924, 0.93419146, 0.94606469])

In [21]:
## recreate sorted correlation matrix
c7 = y2015.corr().abs()

s7 = c7.unstack()
so7 = s7.sort_values(kind="quicksort", ascending=False)

print(so7)

num_tl_90g_dpd_24m              num_tl_90g_dpd_24m                1.000000
il_util                         il_util                           1.000000
mort_acc                        mort_acc                          1.000000
mo_sin_rcnt_tl                  mo_sin_rcnt_tl                    1.000000
mo_sin_old_il_acct              mo_sin_old_il_acct                1.000000
delinq_amnt                     delinq_amnt                       1.000000
chargeoff_within_12_mths        chargeoff_within_12_mths          1.000000
total_cu_tl                     total_cu_tl                       1.000000
inq_fi                          inq_fi                            1.000000
tot_coll_amt                    tot_coll_amt                      1.000000
num_bc_tl                       num_bc_tl                         1.000000
dti_joint                       dti_joint                         1.000000
collections_12_mths_ex_med      collections_12_mths_ex_med        1.000000
recoveries               

In [22]:
y2015 = y2015.drop(columns = ['loan_amnt', 'chargeoff_within_12_mths', 'mo_sin_rcnt_tl'])

In [23]:
## Run Random Forest with cleaned data
rfc6 = ensemble.RandomForestClassifier()
X6 = y2015.drop('loan_status', 1)
Y6 = y2015['loan_status']
X6 = pd.get_dummies(X6)
X6 = X6.dropna(axis=1)

cross_val_score(rfc6, X6, Y6, cv=10)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in versio

array([0.92659875, 0.93094441, 0.91987842, 0.92213436, 0.87102826,
       0.91847542, 0.75162079, 0.92569284, 0.93412022, 0.93537738])

In [26]:
## recreate sorted correlation matrix
c8 = y2015.corr().abs()

s8 = c8.unstack()
so8 = s8.sort_values(kind="quicksort", ascending=False)

print(so8)

num_tl_90g_dpd_24m              num_tl_90g_dpd_24m                1.000000
num_bc_tl                       num_bc_tl                         1.000000
dti                             dti                               1.000000
mths_since_last_record          mths_since_last_record            1.000000
total_rec_late_fee              total_rec_late_fee                1.000000
recoveries                      recoveries                        1.000000
collections_12_mths_ex_med      collections_12_mths_ex_med        1.000000
dti_joint                       dti_joint                         1.000000
tot_coll_amt                    tot_coll_amt                      1.000000
inq_fi                          inq_fi                            1.000000
total_cu_tl                     total_cu_tl                       1.000000
delinq_amnt                     delinq_amnt                       1.000000
mo_sin_old_il_acct              mo_sin_old_il_acct                1.000000
mort_acc                 

In [30]:
y2015 = y2015.drop(columns = ['num_bc_tl', 'mo_sin_old_il_acct', 'mort_acc'])

In [28]:
## Run Random Forest with cleaned data
rfc7 = ensemble.RandomForestClassifier()
X7 = y2015.drop('loan_status', 1)
Y7 = df['loan_status']
X7 = pd.get_dummies(X7)
X7 = X7.dropna(axis=1)

cross_val_score(rfc7, X7, Y7, cv=10)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in versio

array([0.91137707, 0.9269787 , 0.90959607, 0.9229655 , 0.87316552,
       0.91263358, 0.84217151, 0.93725807, 0.91925333, 0.92727877])

### This is still averaging at 90%. We will try one more data clean.

In [31]:
df = y2015

In [32]:
## recreate sorted correlation matrix
c9 = df.corr().abs()

s9 = c9.unstack()
so9 = s9.sort_values(kind="quicksort", ascending=False)

print(so9)

num_tl_90g_dpd_24m              num_tl_90g_dpd_24m                1.000000
mths_since_recent_revol_delinq  mths_since_recent_revol_delinq    1.000000
dti                             dti                               1.000000
mths_since_last_record          mths_since_last_record            1.000000
total_rec_late_fee              total_rec_late_fee                1.000000
recoveries                      recoveries                        1.000000
collections_12_mths_ex_med      collections_12_mths_ex_med        1.000000
dti_joint                       dti_joint                         1.000000
tot_coll_amt                    tot_coll_amt                      1.000000
il_util                         il_util                           1.000000
inq_fi                          inq_fi                            1.000000
total_cu_tl                     total_cu_tl                       1.000000
delinq_amnt                     delinq_amnt                       1.000000
id                       

In [33]:
df = df.drop(columns = ['il_util', 'mths_since_recent_revol_delinq', 'collections_12_mths_ex_med'])

In [34]:
## Run Random Forest with cleaned data
rfc8 = ensemble.RandomForestClassifier()
X8 = y2015.drop('loan_status', 1)
Y8 = df['loan_status']
X8 = pd.get_dummies(X8)
X8 = X8.dropna(axis=1)

cross_val_score(rfc8, X8, Y8, cv=10)

c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)
c:\users\nstow\appdata\local\programs\python\python37\lib\site-packages\sklearn\ensemble\forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in versio

array([0.88193109, 0.92942462, 0.91888105, 0.92329795, 0.87463785,
       0.91688435, 0.76537082, 0.93863545, 0.85852709, 0.87614592])

### We are now below 90% accuracy, so we will use the data before this last cleaning cycle. We will look at that data to determine if it is possible to make these conclusions without information on payment or principle information.

In [35]:
y2015.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421095 entries, 0 to 421094
Data columns (total 31 columns):
id                                421095 non-null float64
term                              421095 non-null object
grade                             421095 non-null object
emp_length                        397278 non-null object
home_ownership                    421095 non-null object
verification_status               421095 non-null object
issue_d                           421095 non-null object
loan_status                       421095 non-null object
pymnt_plan                        421095 non-null object
purpose                           421095 non-null object
title                             420963 non-null object
dti                               421095 non-null float64
mths_since_last_record            74415 non-null float64
initial_list_status               421095 non-null object
total_rec_late_fee                421095 non-null float64
recoveries                     

### It may be possible to perform the Random Forest method without information on payment or principle as there is not a lot of data remaining that relates to those two features. You would probably have to have more features than we have now (31) and the algorithm would not run as efficiently.